name: Node.js Package Lint, Test and Publish

on:
  push:
    branches:
      - "master"

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 1
      - uses: actions/setup-node@v2.1.2
        with:
          node-version: 12
      - run: npm install
      - run: npm ci
      - run: npm run lint
      - run: npm test

  # Publishing to gpr automatically published to npm too
  build-and-publish-gpr:
    needs: lint-and-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 1
      - uses: actions/setup-node@v2.1.2
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
      - run: npm install
      - run: npm ci
      - run: npm run build --if-present
      - run: npm run semantic-release
        env:
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
          GH_TOKEN: ${{secrets.GH_TOKEN}}
          CI: true
  # Uncomment this for a direct publish to npm
  # build-and-publish-npm:
  #   needs: build-and-publish-gpr
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2.3.4
  #       with:
  #         fetch-depth: 1
  #     - uses: actions/setup-node@v2.1.2
  #       with:
  #         node-version: 12
  #         registry-url: https://registry.npmjs.org/
  #     - run: npm ci
  #     - run: npm run build
  #     - run: npm run semantic-release
  #       env:
  #         NPM_TOKEN: ${{secrets.NPM_TOKEN}}
  #         NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
  #         GH_TOKEN: ${{secrets.GH_TOKEN}}
